<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZSCHN01LP0391" failures="1" tests="1" name="runners.UserLoginRunner" time="15.355" errors="0" timestamp="2024-02-08T17:41:47 IST" skipped="0">
  <testcase classname="runners.UserLoginRunner" name="runScenario" time="15.355">
    <failure message="expected [You logged into a secure area!] but found [You logged into a secure Area!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [You logged into a secure area!] but found [You logged into a secure Area!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefinitions.UserLoginStepDef.should_display_success_msg(UserLoginStepDef.java:88)
at âœ½.Should display Success Msg(file:///C:/Workspace/BDDSamplesZuci/src/test/resources/features/UserLogin.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runners.UserLoginRunner -->
